<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Lakbay.Contracts\csharp\Lakbay.Contracts.csproj" />
  </ItemGroup>

</Project>
